---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 45fcbe3f473a0f70737257e566a2d3846a31dd28
    app.quarkus.io/build-timestamp: 2023-08-15 - 14:55:17 +0000
  labels:
    app.kubernetes.io/name: movie-library-app
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: movie-library-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: movie-library-app
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 45fcbe3f473a0f70737257e566a2d3846a31dd28
    app.quarkus.io/build-timestamp: 2023-08-15 - 14:55:17 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: movie-library-app
  name: movie-library-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: movie-library-app
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 45fcbe3f473a0f70737257e566a2d3846a31dd28
        app.quarkus.io/build-timestamp: 2023-08-15 - 14:55:17 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: movie-library-app
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: gtavares/movie-library-app:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: movie-library-app
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
